services:
  jobapprazorweb:
    image: ghcr.io/jaamulberry/jobtrackerrazor:latest
    container_name: JobAppRazorWeb
    ports:
      - "31300:31300"
    environment:
      - TZ=America/Chicago
      - PG_CONNECTION_STRING=Host=<YourHost>;Database=job_tracker;Username=<YourUser>;Password=<YourPassword>
    volumes:
      - /mnt/user/appdata/jobapp:/data
    restart: unless-stopped
    networks:
      - bridge
networks:
  bridge:
    driver: bridge